# Generated by Django 4.0.6 on 2022-07-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superAdmin',
            field=models.BooleanField(default=False, verbose_name='Is superAdmin'),
        ),
    ]
