# Generated by Django 4.0.6 on 2022-07-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_user_is_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favnumOne',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_branchManager',
            field=models.BooleanField(default=False, verbose_name='Is Branch Manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_counterManager',
            field=models.BooleanField(default=False, verbose_name='Is Counter Manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_entityOwner',
            field=models.BooleanField(default=False, verbose_name='Is EntityOwner'),
        ),
        migrations.AddField(
            model_name='user',
            name='order_id',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superAdmin',
            field=models.BooleanField(default=False, verbose_name='Is SuperAdmin'),
        ),
    ]
