# Generated by Django 4.0.6 on 2022-07-27 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_branch_counter_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branchName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='counterName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.counter'),
        ),
        migrations.AddField(
            model_name='user',
            name='entityName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.entity'),
        ),
    ]
