# Generated by Django 4.0.6 on 2022-07-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_user_branchname_user_countername_user_entityname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favnumOne',
        ),
        migrations.RemoveField(
            model_name='user',
            name='order_id',
        ),
    ]
