# Generated by Django 4.0.6 on 2022-07-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_user_favnumone_remove_user_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entityID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
