# Generated by Django 4.0.6 on 2022-07-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_entity_entityid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unUsedKey', models.CharField(max_length=50, null=True)),
                ('usedKey', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Entity',
            new_name='EntityDirectory',
        ),
    ]
