# Generated by Django 4.0.6 on 2022-07-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_licensekey_rename_entity_entitydirectory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityDirectory',
            new_name='EntityDiretories',
        ),
    ]
