# Generated by Django 4.0.6 on 2022-07-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_rename_entitydirectory_entitydiretories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityDiretories',
            new_name='EntityDiretorie',
        ),
    ]
