# Generated by Django 4.0.6 on 2022-07-27 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_rename_entitydiretories_entitydiretorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branchName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='counterName',
        ),
        migrations.AddField(
            model_name='entitydiretorie',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='branchCount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='entityName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
