# Generated by Django 4.0.6 on 2022-07-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_remove_user_branchname_remove_user_countername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entityID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
