# Generated by Django 4.0.6 on 2022-07-28 09:10

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_user_entityid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=50, null=True)),
                ('companyName', models.CharField(max_length=50, null=True)),
                ('mobileNumber', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postalCode', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
