# Generated by Django 4.0.6 on 2022-07-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_supplier_user_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
