# Generated by Django 4.0.6 on 2022-07-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productCode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
