# Generated by Django 4.0.6 on 2022-07-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_product_productcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='Branche',
        ),
    ]
