# Generated by Django 4.0.6 on 2022-07-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_rename_branch_branche'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branchID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
