# Generated by Django 4.0.6 on 2022-07-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_user_branchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branchName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
