# Generated by Django 4.0.6 on 2022-07-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_user_branchname'),
    ]

    operations = [
        migrations.AddField(
            model_name='branche',
            name='entityID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
