# Generated by Django 4.0.6 on 2022-07-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_branche_entityid'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitydiretorie',
            name='branchID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entitydiretorie',
            name='branchName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
