# Generated by Django 4.0.6 on 2022-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_entitydiretorie_branchid_entitydiretorie_branchname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitydiretorie',
            name='user',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
