# Generated by Django 4.0.6 on 2022-07-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_alter_entitydiretorie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.AddField(
            model_name='supplier',
            name='branchID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
