# Generated by Django 4.0.6 on 2022-07-29 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_remove_supplier_user_supplier_branchid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='branchID',
        ),
        migrations.AddField(
            model_name='product',
            name='branchID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
