# Generated by Django 4.0.6 on 2022-07-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_remove_product_user_remove_supplier_branchid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellingCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendorPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
