# Generated by Django 4.0.6 on 2022-07-31 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_alter_product_sellingcost_alter_product_vendorprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDirectorie',
            fields=[
                ('branchName', models.CharField(max_length=50, null=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='billing.entitydiretorie')),
            ],
        ),
        migrations.DeleteModel(
            name='Branche',
        ),
        migrations.RenameField(
            model_name='entitydiretorie',
            old_name='branchID',
            new_name='branchCount',
        ),
        migrations.RemoveField(
            model_name='entitydiretorie',
            name='branchName',
        ),
    ]
