# Generated by Django 4.0.6 on 2022-07-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_branchdirectorie_delete_branche_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchDirectorie',
        ),
    ]
