# Generated by Django 4.0.6 on 2022-07-31 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_delete_branchdirectorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDirectorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=50, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.entitydiretorie')),
            ],
            options={
                'ordering': ['branchName'],
            },
        ),
    ]
