# Generated by Django 4.0.6 on 2022-07-31 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_branchdirectorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountersDirectorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterName', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.AddField(
            model_name='branchdirectorie',
            name='countersCount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='entitydiretorie',
            name='branchID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='countersdirectorie',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.branchdirectorie'),
        ),
    ]
