# Generated by Django 4.0.6 on 2022-07-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_remove_entitydiretorie_branchid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountersDirectorie',
        ),
    ]
