# Generated by Django 4.0.6 on 2022-07-31 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_delete_countersdirectorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountersDirectorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterName', models.CharField(max_length=50, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.branchdirectorie')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.entitydiretorie')),
            ],
        ),
    ]
