# Generated by Django 4.0.6 on 2022-07-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_countersdirectorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countersdirectorie',
            name='entity',
        ),
    ]
