# Generated by Django 4.0.6 on 2022-07-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_remove_countersdirectorie_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branchCount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branchID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branchName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='entityID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='entityName',
        ),
    ]
