# Generated by Django 4.0.6 on 2022-07-31 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_remove_user_branchcount_remove_user_branchid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
