# Generated by Django 4.0.6 on 2022-07-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branchCount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='branchID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='branchName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='entityID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='entityName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
