# Generated by Django 4.0.6 on 2022-07-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_user_branchcount_user_branchid_user_branchname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countersdirectorie',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='BranchDirectorie',
        ),
        migrations.DeleteModel(
            name='CountersDirectorie',
        ),
        migrations.DeleteModel(
            name='EntityDiretorie',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
