# Generated by Django 4.0.6 on 2022-07-31 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_remove_countersdirectorie_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDirectorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=50, null=True)),
                ('countersCount', models.IntegerField(blank=True, default=1, null=True)),
                ('branchID', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['branchName'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50, null=True)),
                ('productCode', models.CharField(max_length=50, null=True)),
                ('sellingCost', models.FloatField(blank=True, null=True)),
                ('vendorPrice', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, default=18, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.branchdirectorie')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='EntityDiretorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityName', models.CharField(max_length=50, null=True)),
                ('entityID', models.CharField(max_length=50, null=True)),
                ('branchCount', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CountersDirectorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterName', models.CharField(max_length=50, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.branchdirectorie')),
            ],
        ),
        migrations.AddField(
            model_name='branchdirectorie',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.entitydiretorie'),
        ),
    ]
