# Generated by Django 4.0.6 on 2022-07-31 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0040_alter_entitydiretorie_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=50, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.branchdirectorie')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50, null=True)),
                ('productCode', models.CharField(max_length=50, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, default=18, null=True)),
                ('invoiceNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.invoiceparent')),
            ],
        ),
    ]
