# Generated by Django 4.0.6 on 2022-07-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0041_invoiceparent_invoicechild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceparent',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.branchdirectorie'),
        ),
    ]
