# Generated by Django 4.0.6 on 2022-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0042_alter_invoiceparent_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicechild',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='invoicechild',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoicechild',
            name='tax',
        ),
        migrations.AddField(
            model_name='invoiceparent',
            name='billAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceparent',
            name='totalProducts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceparent',
            name='totalTax',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
