# Generated by Django 4.0.6 on 2022-07-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0043_remove_invoicechild_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicechild',
            name='productName',
        ),
    ]
